# This is a TOML document.

[general]
version = 1


# http://wiki.ros.org/Remapping%20Arguments
# config parameter will be passed to ros init function
[ros.config]
__name = "dds_ros_bridge"

[ros.writers]

[ros.readers.cloud_sub]
#topic_name = "velodyne_points"
topic_name = "camera/depth/points"
topic_type = "PointCloud2"
qos_queue_size = 1