

[dds.participant]
xml = "bridge_dds_config.xml"
profile = "participant_discovery_protocol_SIMPLE"
name = "dds_ros_bridge_0"
#interface_allowlist = []
#interface_blocklist = []
interface_allowlist = ["lo"]
interface_blocklist = ["eno1", "enx00e04d71ffe7", "wlp4s0", "wlp3s0", "docker0", "wt0"]

[dds.readers]


[dds.writers.cloud_pub]
topic_name = "cloud"
topic_type = "Message::Pointcloud640x480x3"
pub_profile = ""
topic_profile = ""
writer_profile = "shm_writer_profile"
qos_queue_size = 1
