[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-L" ,"/home/waxz/CLionProjects/libroscpp/cmake-build-release-host/install/lib",
    "-l", "ros_helper",
    "-l", "tinyalloc",
    "-l", "ros_helper_message",
    "-l", "ros_helper_impl",
    "-C", "link-arg=-Wl,-rpath,$ORIGIN/../lib",
    "-C", "link-arg=-fuse-ld=gold",
    "-C", "link-arg=-Wl,-rpath,/home/waxz/CLionProjects/libroscpp/cmake-build-release-host/install/lib"
]

