#pi = 3.14159265359
#pi2 = 1.57079632679
[general]
version = 1


[rerun_config]
enable = true
clear = true
#addr = "10.141.110.21:9876"
addr = "127.0.0.1:9876"

robot = [[[-0.4, -0.3], [-0.4, 0.1]], [[1.4, 0.2], [1.4, 0.2]]]
robot_control = [[0.0, 0.0], [0.1, 0.0], [-0.1, 0.0]]
pallet = [[[0.0, -0.5], [0.0, -0.075], [0.0, 0.35]], [[1.4, 0.15], [1.4, 0.15], [1.4, 0.15]]]
path_arrow_len = 0.1
test_relative_start = [0.1,0.0,0.0]

[ros_config]
# enable simalation, publish tf
sim_config = { enable = false, forward_vel_max = 1.5, forward_acc = 1.0, rotate_angle_max = 2.5, rotate_vel = 1.5 }

tf_timeout_s = 0.5
odom_timeout_s = 0.5
request_timeout_s = 1.5
controller_idle_pub_zero_cmd_vel = true
controller_fault_pub_zero_cmd_vel = true
stop_bash = """
rostopic pub -1 /ros_motion_control/cmd_vel geometry_msgs/Twist -- '[0.0, 0.0, 0.0]' '[0.0, 0.0, 0.0]'
"""



# simulation pallet and goal generate
[pallet_generator_config]
# forward:[acc,vel], rotate:[vel,pos]
sim_motor = [1.5, 1.5, 1.7, 1.9]
use_native_or_web = true
path_id = 1
path_nodes2 = [
    [-2.5, 1.0, 3.14159265359],
    [-1.0, 1.0, 3.14159265359],
    [-0.3, 1.0, 3.0],
    [0.0, 1.6, -1.57079632679],
    [0.0, 2.0, -1.57079632679],
    [0.0, 2.3, -1.57079632679],
    [0.0, 3.5, -1.57079632679]
]
path_nodes3 = [
    # line
    [-2.5, 1.0, 3.14159265359],
    # curve
    [-1.0, 1.0, 3.14159265359],
    [-0.4, 1.0, 3.0],
    [0.1, 1.4, -1.57079632679],
    [0.1, 2.0, -1.57079632679],
    [0.1, 2.3, -1.57079632679],
    [0.1, 3.5, -1.57079632679],
    # add
    [0.1, 3.9, -1.47079632679],
    [0.1, 4.5, 3.14159265359],
    [1.1, 4.5, 3.14159265359],
    [2.4, 4.5, 3.14159265359],
]

#back ward
path_nodes = [
    # line
    [-2.5, 1.0, 3.14159265359],
    # curve
    [-1.0, 1.0, 3.14159265359],
    [-0.4, 1.0, 3.0],
    [0.1, 1.4, -1.57079632679],
    [0.1, 2.0, -1.57079632679],
    [0.1, 2.3, -1.57079632679],
    [0.1, 3.5, -1.57079632679],
    # add
    [0.1, 4.2, -1.47079632679],
    [0.4, 4.6, -2.356194490192345],
    [0.9, 5.1, -2.356194490192345],
    [2.4, 6.6, -2.356194490192345],
    # add
    [2.9, 7.1, -1.57079632679],
    [3.3, 7.3, -1.57079632679],
    [3.3, 8.1, -1.57079632679],
    [3.3, 9.6, -1.57079632679],
    ## add line
    #    [3.3, 10.6, -1.57079632679],


    # add
    #    [3.3, 10.2, -1.47079632679],
    #    [3.5, 10.6, 3.14159265359],
    #    [4.1, 10.6, 3.14159265359],
    #    [5.3, 10.6, 3.14159265359],


]

# forward
path_nodesb = [
    # line
    [-2.5, 1.0, 0.0],
    # curve
    [-1.0, 1.0, 0.0],
    [-0.4, 1.0, 0.1],
    [0.1, 1.4, 1.57079632679],
    [0.1, 2.0, 1.57079632679],
    [0.1, 2.3, 1.57079632679],
    [0.1, 3.5, 1.57079632679],
    # add
    [0.1, 4.2, 1.47079632679],
    [0.4, 4.6, 2.356194490192345],
    [0.9, 5.1, 2.356194490192345],
    [2.4, 6.6, 2.356194490192345],
    # add
    [2.9, 7.1, 1.57079632679],
    [3.3, 7.3, 1.57079632679],
    [3.3, 8.1, 1.57079632679],
    [3.3, 9.6, 1.57079632679],
    ## add line
    #    [3.3, 10.6, 1.57079632679],


    # add
    [3.3, 10.2, 1.47079632679],
    [3.5, 10.6, 0.0],
    [4.1, 10.6, 0.0],
    [5.3, 10.6, 0.0],
]

path_nodes1 = [[-2.5, 1.0, 0.0],
    [-1.0, 1.0, 0.0],
    [1.0, 1.0, 0.1],
    [1.0, 2.0, 1.57079632679],
    [1.0, 3.0, 1.57079632679],
    [1.0, 4.0, 1.57079632679],
    [1.0, 5.5, 1.57079632679]]

pallet_config = { pallet_len = 1.2, pallet_shape = [0.5, 0.35, 0.07, -0.07, -0.35, -0.5] }

pallet_init_pose = [2.4, 4.5, 3.14159265359]
pallet_goal_pose = [2.99, 0.0, 3.14159265359]
#pallet_goal_pose = [1.2,0.0,0.0]


forward_goal_pose = [-1.8, 0.0, 3.14159265359]

robot_init_pose = [-2.5, 0.98, 3.14159265359]
robot_init_pose1 = [-2.5, 1.0, 0.0]
robot_init_pose_forward = [-2.5, 0.98, 0.0]

#robot_init_pose = [-1.0,0.98,3.14159265359]

# circle
#robot_init_pose = [-1.0,1.0,1.57]

# face
#robot_init_pose = [-2.0,0.14,2.90159265359]

#robot_init_pose = [-1.0,1.0,3.14159265359]

#robot_init_pose = [0.6,0.0,1.57]

#robot_random_range = [-0.01,0.000005, -0.000005,0.000005,  -0.00005,0.00005]
robot_random_range = [-0.02, 0.02, -0.02, 0.02, -0.02, 0.02]

odom_random_range = [-0.02, 0.02, -0.02, 0.02, -0.000001, 0.000001, ]
#odom_random_range = [-0.015, 0.015,-0.015, 0.015,-0.000001, 0.000001, ]
#odom_random_range = [-0.01, 0.01,-0.01, 0.01,-0.000001, 0.000001, ]
#odom_random_range = [-0.005, 0.005,-0.005, 0.005,-0.000001, 0.000001, ]
#odom_random_range = [-0.001, 0.001,-0.001, 0.001,-0.000001, 0.000001, ]
#odom_random_range = [-0.0001, 0.0001,-0.0001, 0.0001,-0.0001, 0.0001, ]

robot_shape = [0.3, 0.1, -0.1, -0.3]
robot_fork = [-0.2, 1.2]

custom_curve = [
    [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]],
    [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]],
    [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]],
    [[0.0, 0.0], [0.0, 0.0], [0.0, 0.0], [0.0, 0.0]],
]

#robot_path_planner, robot_motion_planner, robot_motion_controller, robot_hardware_control

[robot_path_planner_config]
default_option = "default"
[robot_path_planner_config.options.default]
is_omnidirectional = false
use_start_pose = true
curve_param = [0.6, 0.6, 1.4]
node_interval = 0.04


[robot_motion_planner_config]
model = "SingleSteering"
default_option = "default"
goal_reach_check_num = 3
sliding_len = 20

[robot_motion_planner_config.options.default]
control_program = 1

is_omnidirectional = true
use_front_control_point = true
front_control_point = [0.1, 0.0, 0.0]
front_control_point_low_error = [0.02, 0.0, 0.0]

use_rear_control_point = true
# set control point
rear_control_point = [-0.2, 0.0, 0.0, 0.0]
rear_control_point_low_error = [-0.02, 0.0, 0.0]


##
constrain_start_no_rotate_allow_vel = 0.2

# swich mode from curve to line
switch_line_dist = 0.05
switch_line_path_dist = 1.5
curve_linear_fix = 0.01
curve_search_min = 0.1
curve_search_max = 0.25

# line mode seach valid target
line_search_dist = 0.2
line_search_dist_min = 0.15
# swich mode from line to curve line
line_switch_dist = 0.1
line_search_converge_dist = 0.002
line_search_converge_ratio = 1.0

line_converge_y_acc = 0.05
line_converge_y_min = 0.01
line_converge_y = 0.02
line_converge_yaw = 0.03
line_converge_vel = 0.1


track_curve_vel = 0.1
track_curve_end_vel = 0.1
track_curve_start_vel = 0.1
track_curve_vel_decay_ratio = 5.0
track_curve_vel_decay_min = 0.05
curve_use_closest_direction_dist = 0.015

track_curve_end_dist = 0.9
goal_line_final = 1.0
line_vel = 0.2
final_force_parallel_direction = false
final_relative_target_x = 10.0
goal_line_vel = 0.1
constrain_stop_forward_vel_x_min = 0.001
speed_down_acc = 0.1

path_sparse_dist = 0.2
pose_jump_alert_y = 0.2
pose_jump_alert_x = 0.2
pose_jump_alert_yaw = 0.2

control_closest_alert = 0.3
control_not_converge_check_dist = 0.1
control_not_converge_alert = 0.03

##

start_inplace_rotate_tolerance = 0.05
valid_line_length = 0.5
valid_curve_length = 0.5
line_angle_change = 1e-5
closest_node_search_dist = 0.4


# constrains
constrain_start_no_rotate = false
constrain_start_no_rotate_run_dist = 0.7
constrain_start_no_rotate_allow_offset_y = 0.05
constrain_start_no_rotate_allow_offset_yaw = 0.05

# line to curve vel limit
track_curve_max_vel = 0.1
track_line_to_curve_switch_dist_ratio = 2.0
track_line_to_curve_prediction_normal = 3.0
track_line_to_curve_allow_offset_y = 0.1


track_curve_to_line_switch_dist_ratio = 1.0
track_curve_to_line_search_y = 0.1
track_curve_smooth_direction_ratio = 0.5
track_curve_smooth_direction_offset = 0.03

# final track
track_final_line_prediction_normal = 5.5
track_final_line_forward_vel_y_acc = 0.04
track_final_line_forward_vel_x_max = 0.15
track_final_line_forward_vel_y_max = 0.2
track_final_line_forward_vel_x_min = 0.02
track_final_line_forward_vel_y_min = 0.02
track_final_line_rotate_vel = 0.2
track_final_line_converge_y = 0.005
track_final_line_converge_offset_base_y = 0.1
track_final_line_converge_direction_fix = 0.6
track_final_line_converge_direction_fix_min = 0.02

constrain_stop_forward_vel_y_min = 0.005

reach_goal_num = 2

curve_predict_dist_min = 0.4
curve_predict_dist_max = 0.6

track_line_prediction_normal = 0.99
track_line_prediction_final = 10.11
track_line_prediction_change = 0.5

track_line_allow_offset_y = 0.05
track_line_allow_offset_yaw = 0.05

constrain_stop_no_rotate = true
constrain_stop_no_rotate_run_dist = 1.1
constrain_stop_no_rotate_allow_offset_y = 0.02
constrain_stop_no_rotate_allow_offset_yaw = 0.01


constrain_stop_reaching_dist = 1.3
constrain_stop_allow_offset_x = 0.02

# raise error
constrain_stop_allow_offset_y = 0.05
constrain_stop_allow_offset_yaw = 0.02


allow_final_rotate = false
allow_final_rotate_angle = 0.01
allow_start_offset_dist = 0.3

# allow_goal_dist< 0.0, bypass check
allow_goal_dist = 1.0


allow_first_rotate_start_angle = 0.1


# max forward vel in whole path
allow_forward_vel = 1.0
# when to change to follow_goal mode


allow_curve_forward_vel = 0.4
allow_line_forward_vel = 0.8


start_follow_goal_dist = 1.3
allow_follow_goal_forward_vel = 0.3
follow_goal_no_rotate_on_line = true

start_final_goal_dist = 0.2
allow_final_goal_forward_vel = 0.02


# final low speed

allow_final_forward_dist = 0.1
allow_final_forward_dw_acc = 0.2

# speed down at curve rotation
allow_rotate_vel = 0.9
rotate_check_dist = 0.1


line_offset_tolerance = 0.02

curve_offset_tolerance = 0.045
curve_offset_tolerance_fix = 0.035
curve_offset_converge = 0.003

final_offset_tolerance = 0.02

line_predict_dist_min = 0.4
line_predict_dist_max = 0.9


final_predict_dist_min = 0.4
final_predict_dist_max = 0.9

final_line_predict_dist_min = 1.0
final_line_predict_dist_max = 1.5

final_curve_predict_dist_min = 0.4
final_curve_predict_dist_max = 0.5

[robot_motion_controller_config]
model = "SingleSteering"
default_option = "default"
# define steering wheel mouting position
wheel_mount_pos = [[1.048, 0.0]]
#//SingleSteering:  [[forward_vel_range, forward_vel_acc],[rotate_angle_range, rotate_angle_vel]]
wheel_control_limit = [[1.2, 0.6], [1.9, 0.9]]
wheel_vel_limit = [1.1,0.4]

use_hardware_controller = true
control_interval_s = 0.01
rotate_decay_vel = 0.13
rotate_decay_diff = 0.3

[robot_motion_controller_config.options.default]
rotate_predict_dist = 0.1
rotate_predict_vel = 0.4

inplace_rotate_start_diff = 0.1
inplace_rotate_stop_tolerance = 0.03
inplace_rotate_min_forward_vel = 0.05
inplace_rotate_max_forward_vel = 0.2
inplace_rotate_forward_up_acc = 0.9
inplace_rotate_forward_dw_acc = 0.9
inplace_max_stop_vel_follow_error = 0.1


follow_path_max_forward_vel = 1.2
follow_path_max_forward_up_acc = 0.3
follow_path_max_forward_dw_acc = 0.3



